name: Update README

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests

    - name: Update README
      run: |
        python update_readme.py
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git commit -am "Update contributors in README" --quiet --allow-empty
        git push --quiet
