name: Update README

on:
  push:
    branches:
      - main  # Change to your branch name if necessary

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Change to the Python version you need

    - name: Install dependencies
      run: pip install requests

    - name: Update README
      run: |
        python update_readme.py
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git commit -am "Update contributors in README" || true
        git push
